### searh reservation by customer
GET http://localhost:8080/api/reservation/search/customer?page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoVE02RVlvUURCTXVEbGxhTjh3eFFRPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjMyNDIwNSwiZXhwIjoxNzIyNDEwNjA1fQ.WKb_q53Bf3oJQL8k5HwLkwHUPrL-lylmay7KJcdT0bZFl49n2i5fSzXxIgWHgsK1AdPp-OjWiNMJKj16ZX2O-g

### searh reservation by customer and store
GET http://localhost:8080/api/reservation/search/customer/2/?page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoVE02RVlvUURCTXVEbGxhTjh3eFFRPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjMyNDIwNSwiZXhwIjoxNzIyNDEwNjA1fQ.WKb_q53Bf3oJQL8k5HwLkwHUPrL-lylmay7KJcdT0bZFl49n2i5fSzXxIgWHgsK1AdPp-OjWiNMJKj16ZX2O-g

### searh reservation by partner
GET http://localhost:8080/api/reservation/search/partner/2/?date=2024-07-30&page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJFQTZkVGZtZjRLNEkrSVYxMERLTWVnPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIyNDI0Njk3LCJleHAiOjE3MjI1MTEwOTd9.WvJvqqfUG782PlLal-RGBNK6LfJ77BouULGkgMC6XrmKK3DBqQS7NDVilZMUZ0DT8FUqYf716ATGXRiVHdYDRA
