### searh store by name
GET http://localhost:8080/api/store/search?keyword=광화문&page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIyNDMwNTU4LCJleHAiOjE3MjI1MTY5NTh9.SChWrYvnWXl2jMOJkJj8Su-e3aBglFEL6flA7YCtpKjcyNOJ3xkzCoBhSNlXyLMBOeVs8R8SZteyY9yTIEYw0w

### searh store by alphabetical order
GET http://localhost:8080/api/store/search/alphabet?page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIyNDMwNTU4LCJleHAiOjE3MjI1MTY5NTh9.SChWrYvnWXl2jMOJkJj8Su-e3aBglFEL6flA7YCtpKjcyNOJ3xkzCoBhSNlXyLMBOeVs8R8SZteyY9yTIEYw0w

### searh store by rating order
GET http://localhost:8080/api/store/search/rating?page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIyNDMwNTU4LCJleHAiOjE3MjI1MTY5NTh9.SChWrYvnWXl2jMOJkJj8Su-e3aBglFEL6flA7YCtpKjcyNOJ3xkzCoBhSNlXyLMBOeVs8R8SZteyY9yTIEYw0w

### searh store by distance order
GET http://localhost:8080/api/store/search/distance?address=대구광역시 북구 대학로 85&page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIyNDMwNTU4LCJleHAiOjE3MjI1MTY5NTh9.SChWrYvnWXl2jMOJkJj8Su-e3aBglFEL6flA7YCtpKjcyNOJ3xkzCoBhSNlXyLMBOeVs8R8SZteyY9yTIEYw0w

### searh store
GET http://localhost:8080/api/store/search/detail?id=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIyNDMwNTU4LCJleHAiOjE3MjI1MTY5NTh9.SChWrYvnWXl2jMOJkJj8Su-e3aBglFEL6flA7YCtpKjcyNOJ3xkzCoBhSNlXyLMBOeVs8R8SZteyY9yTIEYw0w

