### create review success
POST http://localhost/api/review
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjU4MjA2MSwiZXhwIjoxNzIyNjY4NDYxfQ.4sUaoUniTuqozKffZYlFB-N3sDlB77exszWq6VXVKn13560tYiYri5Djklcf60-OxNIVlDkMoJ-3PaoTf4XAOQ

{
  "reservationId": "1",
  "rating": 4.3,
  "comment": "후기를 남겨보겠습니다?"
}

### create review success
POST http://localhost/api/review
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoVE02RVlvUURCTXVEbGxhTjh3eFFRPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjMyNDcyNywiZXhwIjoxNzIyNDExMTI3fQ.IuBA2CIy5PGAWxZMRXBaX4KuxQz6m9qZ87gP5CPxujUBx-NcohFv8la3LDWGIUqzR7-uzhiXfQ5lMDyKQkL20g

{
  "reservationId": "2",
  "rating": 2.3,
  "comment": "후기를 남겨보겠습니다다다"
}

### create review success
POST http://localhost/api/review
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoVE02RVlvUURCTXVEbGxhTjh3eFFRPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjMyNDcyNywiZXhwIjoxNzIyNDExMTI3fQ.IuBA2CIy5PGAWxZMRXBaX4KuxQz6m9qZ87gP5CPxujUBx-NcohFv8la3LDWGIUqzR7-uzhiXfQ5lMDyKQkL20g

{
  "reservationId": "3",
  "rating": 3.7,
  "comment": "후기를 남겨보겠습니다아아앙아"
}

### update review success
PATCH http://localhost/api/review
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjUxMDE1NiwiZXhwIjoxNzIyNTk2NTU2fQ.E1aheqa731cRPfNXGD6tqPEkb4MzzBo8AIdTFPc0e1P0EsliraOq9IZzwNi9o6Ptjdsb4oibx9IppCKFnD0gXg

{
  "id": "1",
  "rating": 4.8,
  "comment": "후기를 수정해보겠습니다.?"
}

### delete review by customer success
DELETE http://localhost/api/review/customer?id=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjU4MjA2MSwiZXhwIjoxNzIyNjY4NDYxfQ.4sUaoUniTuqozKffZYlFB-N3sDlB77exszWq6VXVKn13560tYiYri5Djklcf60-OxNIVlDkMoJ-3PaoTf4XAOQ

### delete review by partner success
DELETE http://localhost/api/review/partner?id=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIyNTgyMDM0LCJleHAiOjE3MjI2Njg0MzR9.vcaHILjOGqvcOI6xWdUUgOMifAZL591B0Lmh0yT9zobwzzkyKtIuUBbJpRtEc7rYyR-xXq_LI_JIhItkKmDerg

### search review by customer
GET http://localhost/api/review/search/customer?page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjUxMDE1NiwiZXhwIjoxNzIyNTk2NTU2fQ.E1aheqa731cRPfNXGD6tqPEkb4MzzBo8AIdTFPc0e1P0EsliraOq9IZzwNi9o6Ptjdsb4oibx9IppCKFnD0gXg

### search review by partner and store
GET http://localhost/api/review/search/partner?storeId=1&page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLei9BSlZhVDlLcHZpQ1ZicGY3cjdRPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6WyJST0xFX1BBUlRORVIiXSwiaWF0IjoxNzIyNDMwNTU4LCJleHAiOjE3MjI1MTY5NTh9.SChWrYvnWXl2jMOJkJj8Su-e3aBglFEL6flA7YCtpKjcyNOJ3xkzCoBhSNlXyLMBOeVs8R8SZteyY9yTIEYw0w
