### searh store by name
GET http://localhost/api/store/search?name=keyword&page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjU4MTM3MCwiZXhwIjoxNzIyNjY3NzcwfQ.VGV7FKxLPIiAUhsEVdRfXwgxbsT2w-LRiaYEiWHBOw9BIZRPedJ98Zz89OC1puzpSrmN0XChltnVK_jR-IKxAg

### searh store by alphabetical order
GET http://localhost/api/store/search/alphabet?page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjU4MTM3MCwiZXhwIjoxNzIyNjY3NzcwfQ.VGV7FKxLPIiAUhsEVdRfXwgxbsT2w-LRiaYEiWHBOw9BIZRPedJ98Zz89OC1puzpSrmN0XChltnVK_jR-IKxAg

### searh store by rating order
GET http://localhost/api/store/search/rating?page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjU4MTM3MCwiZXhwIjoxNzIyNjY3NzcwfQ.VGV7FKxLPIiAUhsEVdRfXwgxbsT2w-LRiaYEiWHBOw9BIZRPedJ98Zz89OC1puzpSrmN0XChltnVK_jR-IKxAg

### searh store by distance order
GET http://localhost/api/store/search/distance?address=대구광역시 북구 대학로 85&page=0&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjU4MTM3MCwiZXhwIjoxNzIyNjY3NzcwfQ.VGV7FKxLPIiAUhsEVdRfXwgxbsT2w-LRiaYEiWHBOw9BIZRPedJ98Zz89OC1puzpSrmN0XChltnVK_jR-IKxAg

### searh store
GET http://localhost/api/store/search/detail?id=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYWg0WSthVnpjbzNDMDYwYWMvRk1nPT0iLCJqdGkiOiJTdWJIZUtVUlJyZVFZK1dTT25Ca3RnPT0iLCJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sImlhdCI6MTcyMjU4MTM3MCwiZXhwIjoxNzIyNjY3NzcwfQ.VGV7FKxLPIiAUhsEVdRfXwgxbsT2w-LRiaYEiWHBOw9BIZRPedJ98Zz89OC1puzpSrmN0XChltnVK_jR-IKxAg

